<a href="https://colab.research.google.com/github/Omadbek-mark/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.2.3

In [5]:
mydataset = {
    'cars':['BMW', "Volvo", 'Ford', 'Tesla', 'Ferrari', 'Ford', "Mers"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6     Mers       3

In [6]:
df.head(5) # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [7]:
df.tail(-1) # default 5 rows

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6     Mers       3

In [8]:
df.shape

(7, 2)

In [10]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [11]:
df.dtypes

cars      object
counts     int64
dtype: object

In [13]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6     Mers       3

In [12]:
df.describe() # numerical columns only

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [14]:
df.iloc[0]

cars      BMW
counts      3
Name: 0, dtype: object

In [16]:
df.loc[2:5, 'cars']

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [17]:
df[df['counts'] > 3]

    cars  counts
1  Volvo       7
3  Tesla       8
5   Ford       9

In [ ]:
# df.mean(numeric_only=True)
df['counts'].mean()

In [18]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordMers
counts                                  33
dtype: object

In [19]:
df.min()

cars      BMW
counts      1
dtype: object

In [21]:
df.max()

cars      Volvo
counts        9
dtype: object

In [22]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [23]:
df.count()

cars      7
counts    7
dtype: int64

In [25]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [3]:
import pandas as pd

In [4]:
data_with_missing = {
    'cars': ['BMW', 'Volvo', None, 'Tesla', "ferrari", None, 'Ford'],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(data_with_missing)

{'cars': ['BMW', 'Volvo', None, 'Tesla', 'ferrari', None, 'Ford'], 'counts': [3, 7, None, 8, 1, 9, None]}

In [5]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [10]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  ferrari     1.0
6     Ford     NaN

In [16]:
df_missing.fillna({'cars': 'unknown', "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [23]:
# df = pd.read_csv("Titanic-Dataset.csv")

df = pd.read_excel("test.xlsx")

df.tail()

# df = pd.read_excel("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [21]:
df.to_excel("test.xlsx")

In [24]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [25]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'ferrari', None, 'Ford']